services:
  streamlit:
    build:
      context: .
    container_name: streamlit
    ports:
      - 8501:8501
    env_file : .env
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
      - DATABASE=${DATABASE}
    volumes:
      - type: bind
        source: ./viz
        target: /app
